### ISSUE TITLE
[Feature Request] Auto-refresh on DOM changes

### ISSUE THREAD

**Issue by joegaffey** [Matsuuu/web-component-devtools#12]
Excellent tool - great job! 
WouId be nice to have an option to auto refresh the WC tree on changes to the inspected page DOM.

**Comment by Matsuuu** [comment]
Hi Joe,

Currently there are systems in play that attempt to keep the WC tree up to date on DOM changes, utilizing MutationObservers.

What is a use case in which the WC tree update didn't trigger? Could you give me a re-producable demo so that I can get this edge case sorted out :)

**Comment by joegaffey** [comment]
I'm afraid I can't share the code but I had another look and it seems like does actually work much of the time (more than when I first tried). It is turning into a bit of a heisenbug as it's quite intermittent now and sometimes it just takes a while for the tree to refresh. I'll keep testing and see if I can isolate a root cause.

**Comment by Matsuuu** [comment]
Heya,

I actually had a hunch that this might be an actual bug/oversight and was able to re-prod it.

I've put a mutation observer in place to observe the mutations in the light DOM, but any elements inside a shadow DOM of an element are being ignored by this, meaning that if you for example add a item onto a list inside a shadow DOM, it doesn't get updated in the tree.

This will be fixed in 0.1.3

**Comment by Matsuuu** [comment]
Fixed [here](https://github.com/Matsuuu/web-component-devtools/commit/227ed264f2e5aa1f5f84dace2c6e6ee0622023d9) and [here](https://github.com/Matsuuu/web-component-devtools/commit/18dec77e3993e89e0220d26308c4dabfa099462f).

Will ship in 0.1.3
