### ISSUE TITLE
[BUG]: high cpu usage on pages with many tables on Firefox

### ISSUE THREAD

**Issue by blikblum** [Matsuuu/web-component-devtools#58]
**Describe the bug**
In a page with many tables ou one big table cpu usage is high. Tested on Firefox

**To Reproduce**
1. Go to a page with a table element with many rows
2. Look at cpu usage

**Expected behavior**
The extension should not lead to high cpu usage

**Screenshots**
![image](https://user-images.githubusercontent.com/3047126/215318216-b8dce261-e1a6-4a8b-b5d4-ec43f6b30503.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 109

**Additional context**
The extension is walking in all elements with shadowRoot regardless of being custom elements or not, calling initDomMutationObservers (see the callstack (Pilha de chamadas) in screenshot)

Since there are many th, td elements this consumes a lot of time

One solution is to check if element is a custom-element in `elementHasShadowRoot`

**Comment by Matsuuu** [comment]
Heya @blikblum !

Thank you for the thorough report!

>One solution is to check if element is a custom-element in elementHasShadowRoot

Yeah this part of the extension is something that hasn't got as much care as it should, and this is something that needs to be fixed.

I'll try to find some time within the next week to push a fix to this.

**Comment by Matsuuu** [comment]
Found some time to look at this and I think I found the reason for this happening and it should be fixed in the 0.2.1 update.

However... I notice you are using Firefox as your plugin platform an unfortunately they don't 100% support the Manifest v3 version of extension yet, so I am not able to update it just yet. I need to do some compatibility work with it to get it working on Firefox. 

Until then, you can wait for the 0.2.1 version to ship for Chrome and use it through Google Chrome

**Comment by Matsuuu** [comment]
Let's close this one too and re-open if the problem exists after the 0.2.1 version update

**Comment by blikblum** [comment]
Many thanks. I will take a look
